from src.day08.day08 import get_unique_counts


def test_example_part_1():
    blocks = [
        "fdgacbe",
        "cefdb",
        "cefbgd",
        "gcbe",
        "fcgedb",
        "cgb",
        "dgebacf",
        "gc",
        "cg",
        "cg",
        "fdcagb",
        "cbg",
        "efabcd",
        "cedba",
        "gadfec",
        "cb",
        "gecf",
        "egdcabf",
        "bgf",
        "bfgea",
        "gebdcfa",
        "ecba",
        "ca",
        "fadegcb",
        "cefg",
        "dcbef",
        "fcge",
        "gbcadfe",
        "ed",
        "bcgafe",
        "cdgba",
        "cbgef",
        "gbdfcae",
        "bgc",
        "cg",
        "cgb",
        "fgae",
        "cfgab",
        "fg",
        "bagce",
    ]

    assert get_unique_counts(blocks) == 26
